# Generated by Django 3.1.1 on 2020-10-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appApartment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('check_in_date', models.DateField(verbose_name='Fecha de CheckIn')),
                ('check_out_date', models.DateField(verbose_name='Fecha de CheckOut')),
                ('booking_payment', models.PositiveIntegerField(verbose_name='Pago de reserva')),
                ('total_value', models.PositiveIntegerField(verbose_name='Valor total de reserva')),
                ('registration_date', models.DateField(verbose_name='Fecha de Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿El registro está activo?')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appApartment.apartment', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'db_table': 'rent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rent State',
                'verbose_name_plural': 'Rents States',
                'db_table': 'rent_state',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('rut', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de rut')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'db_table': 'resident',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employee', models.BooleanField(default=False, verbose_name='¿Es funcionario?')),
                ('is_client', models.BooleanField(default=False, verbose_name='¿Es cliente?')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRent.rent', verbose_name='Arriendo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rent User',
                'verbose_name_plural': 'Rents Users',
                'db_table': 'rent_user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentResident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Registro activo?')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRent.rent', verbose_name='Arriendo')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRent.resident', verbose_name='Huesped')),
            ],
            options={
                'verbose_name': 'Rent Resident',
                'verbose_name_plural': 'Rents Residents',
                'db_table': 'rent_resident',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='resident',
            field=models.ManyToManyField(through='appRent.RentResident', to='appRent.Resident', verbose_name='Huespedes'),
        ),
        migrations.AddField(
            model_name='rent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRent.rentstate', verbose_name='Estado de la Reserva'),
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ManyToManyField(through='appRent.RentUser', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
