# Generated by Django 3.1.1 on 2020-10-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price_per_person', models.PositiveSmallIntegerField(verbose_name='Precio por persona')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿El registro está activo?')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tour',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.CharField(max_length=8, verbose_name='Patente')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacidad de pasajeros')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TourDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del Tour')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appExtraService.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour Description',
                'verbose_name_plural': 'Tours Descriptions',
                'db_table': 'tour_clob',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceScheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField(verbose_name='Fecha agendada')),
                ('price', models.PositiveIntegerField(verbose_name='Valor de servicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿El registro está activo?')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExtraService.vehicle', verbose_name='Vehiculo asignado')),
            ],
            options={
                'verbose_name': 'Service Scheduled',
                'verbose_name_plural': 'Services Scheduleds',
                'db_table': 'service_scheduled',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del Servicio')),
                ('scheduled', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appExtraService.servicescheduled', verbose_name='Agenda de servicio')),
            ],
            options={
                'verbose_name': 'scheduled description',
                'verbose_name_plural': 'scheduled description',
                'db_table': 'svc_scheduled_clob',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TourScheduled',
            fields=[
                ('servicescheduled_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appExtraService.servicescheduled')),
                ('people_total', models.PositiveSmallIntegerField(verbose_name='Total de personas')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExtraService.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour Scheduled',
                'verbose_name_plural': 'Tours Scheduleds',
                'db_table': 'tour_scheduled',
                'ordering': ['id'],
            },
            bases=('appExtraService.servicescheduled',),
        ),
        migrations.CreateModel(
            name='TransportScheduled',
            fields=[
                ('servicescheduled_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appExtraService.servicescheduled')),
                ('meeting_place', models.CharField(max_length=200, verbose_name='Lugar de encuentro')),
                ('destination_place', models.CharField(max_length=200, verbose_name='Lugar de destino')),
            ],
            options={
                'verbose_name': 'Transport Scheduled',
                'verbose_name_plural': 'Transports Scheduleds',
                'db_table': 'transport_scheduled',
                'ordering': ['id'],
            },
            bases=('appExtraService.servicescheduled',),
        ),
    ]
