# Generated by Django 3.1.1 on 2020-10-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appExtraService', '0001_initial'),
        ('appApartment', '0001_initial'),
        ('appRent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateField(auto_now=True, verbose_name='Fecha de acción de pago')),
                ('register_action', models.DateField(auto_now_add=True, verbose_name='Fecha de creación de registro')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto pagado')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appApartment.apartment', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Apartment Cost',
                'verbose_name_plural': 'Apartment Costs',
                'db_table': 'apartment_cost',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pyment Type',
                'verbose_name_plural': 'Pyments Type',
                'db_table': 'pyment_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pyment', models.DateField(auto_now=True, verbose_name='Fecha de acción de pago')),
                ('register_pyment', models.DateField(auto_now_add=True, verbose_name='Fecha de creación de registro')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto pagado')),
                ('pyment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinance.pymenttype', verbose_name='Medio de pago')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExtraService.servicescheduled', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Service Pyment',
                'verbose_name_plural': 'Service Pyments',
                'db_table': 'service_pyment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentPyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pyment', models.DateField(auto_now=True, verbose_name='Fecha de acción de pago')),
                ('register_pyment', models.DateField(auto_now_add=True, verbose_name='Fecha de creación de registro')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto pagado')),
                ('pyment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinance.pymenttype', verbose_name='Medio de pago')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRent.rent', verbose_name='Arriendo')),
            ],
            options={
                'verbose_name': 'Rent Pyment',
                'verbose_name_plural': 'Rent Pyments',
                'db_table': 'rent_pyment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AptCostDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del Gasto')),
                ('apt_cost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFinance.aptcost', verbose_name='Registro de Costo')),
            ],
            options={
                'verbose_name': 'Apartmen Cost Description',
                'verbose_name_plural': 'Apartment Cost Descriptions',
                'db_table': 'apt_cost_clob',
                'ordering': ['id'],
            },
        ),
    ]
